#!/bin/bash -xe

DOMAIN="lu3k.link"
BUCKET="lu3k-kops-state"
CLUSTER_CONFIG="$HOME/GitHub/practices/k8s/kops/clusters/basic/$DOMAN.yaml"
export NAME="$DOMAIN"
export KOPS_STATE_STORE="s3://$BUCKET"

echo "=> Create Cluster Config"
kops create -f $CLUSTER_CONFIG

echo "=> Create Cluster in AWS"
kops update cluster --name $NAME --admin --yes


echo "=> Wait for Cluster to be ready ..."
kops validate cluster --wait 10m