#!/bin/bash -xe

DOMAIN="lu3k.link"
BUCKET="lu3k-kops-state"
CLUSTER_CONFIG="$HOME/GitHub/practices/k8s/kops/clusters/basic/$DOMAIN.yaml"
export NAME="$DOMAIN"
export KOPS_STATE_STORE="s3://$BUCKET"

date
echo "=> Create Cluster Config"
time kops create -f $CLUSTER_CONFIG

echo "=> Create Cluster in AWS"
time kops update cluster --name $NAME --admin --yes


echo "=> Wait for Cluster to be ready ..."
time kops validate cluster --wait 10m
date